version: 2
updates:
  - package-ecosystem: cargo
    directory: /bufferfish-rs
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      prefix-development: "build"

  - package-ecosystem: npm
    directory: /bufferfish-ts
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      prefix-development: "build"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      prefix-development: "build"
